-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Dphones.Enum.Track_constraint exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| unique or primary key constraints on table "track"

  - Track\_pkey - unique or primary key constraint on columns "url"

-}
type Track_constraint
    = Track_pkey


list : List Track_constraint
list =
    [ Track_pkey ]


decoder : Decoder Track_constraint
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "track_pkey" ->
                        Decode.succeed Track_pkey

                    _ ->
                        Decode.fail ("Invalid Track_constraint type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : Track_constraint -> String
toString enum____ =
    case enum____ of
        Track_pkey ->
            "track_pkey"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Track_constraint
fromString enumString____ =
    case enumString____ of
        "track_pkey" ->
            Just Track_pkey

        _ ->
            Nothing
