-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Dphones.Object.Track exposing (..)

import Dphones.InputObject
import Dphones.Interface
import Dphones.Object
import Dphones.Scalar
import Dphones.ScalarCodecs
import Dphones.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


album : SelectionSet String Dphones.Object.Track
album =
    Object.selectionForField "String" "album" [] Decode.string


{-| An object relationship
-}
appearsOn :
    SelectionSet decodesTo Dphones.Object.Album
    -> SelectionSet (Maybe decodesTo) Dphones.Object.Track
appearsOn object____ =
    Object.selectionForCompositeField "appearsOn" [] object____ (Basics.identity >> Decode.nullable)


index : SelectionSet (Maybe Int) Dphones.Object.Track
index =
    Object.selectionForField "(Maybe Int)" "index" [] (Decode.int |> Decode.nullable)


plays : SelectionSet Int Dphones.Object.Track
plays =
    Object.selectionForField "Int" "plays" [] Decode.int


title : SelectionSet String Dphones.Object.Track
title =
    Object.selectionForField "String" "title" [] Decode.string


url : SelectionSet String Dphones.Object.Track
url =
    Object.selectionForField "String" "url" [] Decode.string
